receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5317
      http:
        endpoint: 0.0.0.0:5318

exporters:
  otlp/main_collector:
    endpoint: "${MAIN_COLLECTOR_HOST}:4317"   # IP server1, порт OTLP gRPC
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/main_collector]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/main_collector]