{
 "title": "Service Health with Dependencies",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "ApiGatewayService",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_health_status{service=\"ApiGatewayService\"} or dependency_health_status{service=\"ApiGatewayService\"}",
     "legendFormat": "{{service}} {{dependency}}"
    }
   ]
  },
  {
   "title": "UserService",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_health_status{service=\"UserService\"} or dependency_health_status{service=\"UserService\"}",
     "legendFormat": "{{service}} {{dependency}}"
    }
   ]
  },
  {
   "title": "OrderService",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_health_status{service=\"OrderService\"} or dependency_health_status{service=\"OrderService\"}",
     "legendFormat": "{{service}} {{dependency}}"
    }
   ]
  },
  {
   "title": "ProductService",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "service_health_status{service=\"ProductService\"} or dependency_health_status{service=\"ProductService\"}",
     "legendFormat": "{{service}} {{dependency}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket{http_route!=\"/health/ready\"}[1m])) by (exported_job, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"[45]..\",http_route!=\"/health/ready\"}[5m]))\r\n  by (http_response_status_code, le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество ошибок по статусам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"[45]..\", http_route!=\"/health/ready\"}[1m]))\r\nby (http_response_status_code)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95-й процентиль длительности для 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"5..\", http_route!=\"/health/ready\"}[1m]))\r\n  by (http_response_status_code, le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " 95-й процентиль длительности для 4xx:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\r\n  sum(rate(http_server_request_duration_seconds_bucket{http_response_status_code=~\"4..\", http_route!=\"/health/ready\"}[1m]))\r\n  by (http_response_status_code, le)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}